"""added tags table

Revision ID: 5eb71e4ef3ca
Revises: ea9de5f8f04e
Create Date: 2025-01-18 00:29:52.017735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5eb71e4ef3ca'
down_revision: Union[str, None] = 'ea9de5f8f04e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('booktag',
    sa.Column('bookId', sa.Uuid(), nullable=False),
    sa.Column('tagId', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['bookId'], ['books.uid'], ),
    sa.ForeignKeyConstraint(['tagId'], ['tags.uid'], ),
    sa.PrimaryKeyConstraint('bookId', 'tagId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booktag')
    op.drop_table('tags')
    # ### end Alembic commands ###
