"""added tags column to books table

Revision ID: a19334a6ed6b
Revises: 5eb71e4ef3ca
Create Date: 2025-01-18 00:34:32.289254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a19334a6ed6b'
down_revision: Union[str, None] = '5eb71e4ef3ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
